### PR TITLE
Bump [compat] for MLJBase="1"

### LINKED ISSUE #11: Dev branch failing julia 1.7 tests
Although Julia 1.8 and 1.9 tests are passing (see #9) Julia 1.7 tests appear to fail on current dev: #10

### PR DESCRIPTION
**Pull request by ablaom**
Also resolves #11 and replaces #14

### CODE REVIEW

**Comment by ablaom** [comment]
If you're happy, please merge, make a PR onto dev, and tag a new release. I've already bumped the version to 0.1.1.

**Comment by ablaom** [comment]
I see, Xoshiro is unsupported for Julia 1.6 and only added in 1.7 I'm going to change that to MersenneTwister for 1.6.

**Comment by ablaom** [comment]
Second thoughts, that's going to be a little messy. Let's add 1.6 support in a separate PR. 

This PR to only support and test julia >= 1.7

**Comment by ablaom** [comment]
Okay, it seems to me the fail is not from this PR but because the [latest commit](https://github.com/JuliaAI/MLJBalancing.jl/commit/0ae67c7c524998caabaeae9850f7525778e9212b) to dev is failing. 

@EssamWisam Did you push an untested commit directly to dev (ie, not via a PR)?

**Comment by EssamWisam** [comment]
> Okay, it seems to me the fail is not from this PR but because the [latest commit](https://github.com/JuliaAI/MLJBalancing.jl/commit/0ae67c7c524998caabaeae9850f7525778e9212b) to dev is failing.
> 
> @EssamWisam Did you push an untested commit directly to dev (ie, not via a PR)?

@ablaom  Certain that I tested locally before pushing. Let me see what's going on.

Edit: confirming that tests run perfect locally.

**Comment by ablaom** [comment]
This is what I'm getting for current dev, testing locally:

```julia
     Testing Running tests...
Test Summary:                                    | Pass  Total  Time
group_inds and get_majority_minority_inds_counts |    3      3  2.0s
BalancedBaggingClassifier: Error During Test at /Users/anthony/GoogleDrive/Julia/MLJ/MLJBalancing/test/balanced_bagging.jl:13               
  Got exception outside of a @test
  MethodError: no method matching generate_imbalanced_data(::Int64, ::Int64; cat_feats_num_vals::Vector{Int64}, probs::Vector{Float64}, type::String, rng::Int64)
  
  Closest candidates are:
    generate_imbalanced_data(::Integer, ::Integer; means, min_sep, stds, num_vals_per_category, class_probs, type, insert_y, rng) got unsupported keyword arguments "cat_feats_num_vals", "probs"                            
     @ Imbalance ~/.julia/packages/Imbalance/WfR6b/src/extras.jl:107
  
  Stacktrace:
    [1] kwerr(::NamedTuple{(:cat_feats_num_vals, :probs, :type, :rng), Tuple{Vector{Int64}, Vector{Float64}, String, Int64}}, ::Function, ::Int64, ::Int64)
      @ Base ./error.jl:165
    [2] macro expansion
      @ ~/GoogleDrive/Julia/MLJ/MLJBalancing/test/balanced_bagging.jl:14 [inlined]
    [3] macro expansion
      @ /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
    [4] top-level scope
      @ ~/GoogleDrive/Julia/MLJ/MLJBalancing/test/balanced_bagging.jl:14
    [5] include(fname::String)
      @ Base.MainInclude ./client.jl:478
    [6] top-level scope
      @ ~/GoogleDrive/Julia/MLJ/MLJBalancing/test/runtests.jl:10
    [7] include(fname::String)
      @ Base.MainInclude ./client.jl:478
    [8] top-level scope
      @ none:6
    [9] eval
      @ ./boot.jl:370 [inlined]
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:280
   [11] _start()
      @ Base ./client.jl:522
Test Summary:             | Error  Total  Time
BalancedBaggingClassifier |     1      1  2.2s
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/anthony/GoogleDrive/Julia/MLJ/MLJBalancing/test/balanced_bagging.jl:13
in expression starting at /Users/anthony/GoogleDrive/Julia/MLJ/MLJBalancing/test/runtests.jl:10
ERROR: Package MLJBalancing errored during testing
```

which is the same error I'm seeing for this PR. 

```julia
julia>  versioninfo()
Julia Version 1.9.1
Commit 147bdf428cd (2023-06-07 08:27 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 12 × Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 5 on 12 virtual cores
Environment:
  JULIA_LTS_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_PATH = /Applications/Julia-1.9.app/Contents/Resources/julia/bin/julia
  JULIA_EGLOT_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
  JULIA_NIGHTLY_PATH = /Applications/Julia-1.9.app/Contents/Resources/julia/bin/julia
```

**Comment by EssamWisam** [comment]
No idea why I don't see this here. Thank you for sharing, trying to reproduce.

It seems like that I missed that my change of a keyword argument name in `generate_imbalanced_data` in `Imbalance.jl` is in fact breaking. It must be using the most recent release that we just rolled out two hours ago.

**Comment by EssamWisam** [comment]
@ablaom updated `Imbalance.jl` in `MLJBalancing.jl` environment and was able to reproduce. Changed variable names and now all tests and examples run successfully.

**Comment by ablaom** [comment]
Again, I'm guessing the fail here is unrelated to this PR. See #11.

**Pull request merged**
